### ISSUE TITLE
Cannot edit a proposal

### ISSUE THREAD

**Issue by nodunayo** [nodunayo/speakerline#1]
At the moment, there is no ability to edit proposals on the front-end of the site.

**Comment by jemagee** [comment]
Is this as simple as creating an edit function on proposals, or do you with to add an authentication system (perhaps devise?) that limits who can edit a proposal to who submitted it?

**Comment by nodunayo** [comment]
It involves exposing the `edit` Controller action and the route too. Don't want to add in any authentication for the time being. I'm thinking about this more as an open wiki for now.

**Comment by jemagee** [comment]
I think I can do that (hopefully) though the testing would most likely be RSpec TDD instead of BDD if I did it (i'm rewwriting my migration right now though - I think i have it now - my original commit the rollback actually had an error in it that I didn't catch)
