### ISSUE TITLE
You can add and edit tags up to three tags on a proposal

### ISSUE THREAD

**Issue by nodunayo** [nodunayo/speakerline#122]
We need a better way for users to find proposals that interest them. Therefore, I propose adding the ability to add tags to a proposal upon creating it as well as the ability to edit them.

I also want to limit tags to 3 so that tags are more useful for organisation and finding purposes. It's also a useful tool for speakers struggling to choose three tags to wonder whether their proposal covers too much scope!

In a separate chunk of work, we can add the ability to filter proposals down by tags.

**Comment by andrew** [comment]
@nodunayo you should add the "help wanted" label ;)
