### ISSUE TITLE
Add ability to search proposals by title and body

### ISSUE THREAD

**Issue by nodunayo** [nodunayo/speakerline#123]
Sometimes looking at a list of speaker's names, proposal titles, or events isn't quite what you need. Sometimes, you want to search for a keyword or two and see what's out there. For those people, I propose that we add the ability to search proposals by their title and body.

Also, as the database grows (hopefully!) search will be even more useful.

**Comment by andrew** [comment]
@nodunayo you should add the "help wanted" label ;)

**Comment by nodunayo** [comment]
@esmale Thanks, David! :-D
