### ISSUE TITLE
Style error messages

### ISSUE THREAD

**Issue by nodunayo** [nodunayo/speakerline#154]
At the moment, if a user does not fill out a form correctly, the error messages look like this:

![Screen Shot 2019-04-19 at 10 34 42](https://user-images.githubusercontent.com/4911302/56418467-e1855300-628e-11e9-8ee5-37fb8f8c5fdc.png)

It would be nice to style them a little to improve the US. Perhaps a border and background colour?

**Comment by hilarysk** [comment]
Working on this one :)

**Comment by nodunayo** [comment]
Thanks, Hilary!
