### ISSUE TITLE
Year as an Integer?

### ISSUE THREAD

**Issue by jemagee** [nodunayo/speakerline#17]
Is there a specific reason that year isn't an integer?  It can still be easily manipulated for display the way it's done, but keeping it as an integer also allows for more flexible searching in the future (i.e. i want to see all conferences in the last 2 years for instance)

**Comment by nodunayo** [comment]
Yes, this is something that definitely needs fixing, particularly to enable ordering/searching in the future.

**Comment by jemagee** [comment]
WEll, the reason I ask is that I think it's something I can handle right away :) I'm good with rspec, and capybara, but haven't done any BDD with cucumber so need to pick it up a bit.

**Comment by nodunayo** [comment]
Well, please go ahead! :-)

I used Cucumber as it's something that I'm familiar with and BDD helps my development workflow. I wonder if it'll be a barrier to more contributors...

**Comment by jemagee** [comment]
I don't think it should be, at least for me, it just makes me more motivated to pick up a new skill...my own project i've been holding off on launching because most who expressed interested are in JS but I tried ember last weekend to see how it felt and it just felt overly complicated when compared to rails

**Comment by nodunayo** [comment]
>  it just makes me more motivated to pick up a new skill

Yay!

**Comment by jemagee** [comment]
I reset my copy to the master here and deleted the branch I made (which deleted the pull request)..I think I have a way to do this, but not sure how to test it
