### ISSUE TITLE
`Title` field on New Proposal Page does not support Markdown

### ISSUE THREAD

**Issue by nodunayo** [nodunayo/speakerline#3]
Justin's proposal title isn't rendering as he expected it to: http://speakerline.io/proposals/9.

Perhaps the `title` field should support Markdown too?

**Comment by jemagee** [comment]
It could support markdown if you wanted, I have set up markdown (using kramdown) in my own blog, but I also have some experience setting up tinymce (wysiwyg) a little - the only issue is you have to turn off turbolinks which most people seem to suggest.  

In my personal opinion though, I would standardize the title of proposals and such and only allow markdown within the body.

**Comment by nodunayo** [comment]
Well, I've currently got `redcarpet` set up to parse the body of the proposal, so adding it to the `title` field shouldn't be tricky.

However, like you suggest, I'm not sure it's something we should enable. People wanting formatting in their title is rare, I suspect.

I'm going to close this and we'll see if it's something people end up wanting.
