### ISSUE TITLE
Speakers with no proposals should not show up on the homepage

### ISSUE THREAD

**Issue by nodunayo** [nodunayo/speakerline#32]
It's not helpful to have people visiting the site clicking on a speaker's name and getting a blank page.

Let's hide speakers in the DB who don't have any proposals attached to them.

**Comment by flyinggrizzly** [comment]
@nodunayo I'll hop on this one too if that's cool?

**Comment by flyinggrizzly** [comment]
@nodunayo thinking about this, should this change also include a link to a view where all users are visible? 

I can defo see a scenario where a new user is added and then lost so they can’t add proposals because they don’t know their record id. 

Basically, should we add an `index_all` action that shows all users and include a link to it on the index view?

**Comment by nodunayo** [comment]
@flyinggrizzly — let's leave out the link for all speakers for now. I don't think there's much value at the moment in seeing a list of speakers (as opposed to users) who don't have any proposals attached to them.

When you add a proposal, you select by name (on the form), as opposed to ID. If you try and add a speaker with the same name as one already in the DB, you'll get an error. If we start getting messy duplicates, then we can think about how we better handle this.

Is that okay with you?

Thank you for picking this up and for all of your work today! :-)

**Comment by flyinggrizzly** [comment]
That makes sense. I've got it working without, but it's breaking the feature test for adding users (which currently tests that added users appear in the index view, which no longer happens unless you also create a proposal at the same time... which is mixing the testing).

Will submit a PR once I figure that out!

**Comment by nodunayo** [comment]
@flyinggrizzly Cool.

Yes, I reckon the tests will need to take a different direction then!

**Comment by nodunayo** [comment]
Still being worked on as there was a bug in PR#53

**Comment by nodunayo** [comment]
Thanks @flyinggrizzly for your great work!
