### ISSUE TITLE
Speaker index page is not one long list

### ISSUE THREAD

**Issue by nodunayo** [nodunayo/speakerline#33]
At the moment, when you visit the '/speakers' you get one long list, like so:

![screen shot 2017-11-27 at 17 44 55](https://user-images.githubusercontent.com/4911302/33280660-b77465da-d39a-11e7-9835-c1ccbe9480af.png)

It would be great to find a way to better display the information. Perhaps columns?

Even better would be a solution that adapts to an ever-growing speaker list (🤞) rather than one that fits the number of speakers we currently have.

**Comment by olwend** [comment]
I've started looking at this - initially grouping to display Letter - items. 
Next steps to click/expand letter to display sub items
Finally be able to scroll through a smaller display box

**Comment by nodunayo** [comment]
Hey Olwen,

Yay, glad you're picking this up.

Could you maybe draw a little sketch of what the page would look like when you first went onto it?

Just trying to visualise what you wrote above and want to make sure we're doing the simplest thing that's also easily maintainable. 

Thanks,

Nadia

**Comment by olwend** [comment]
Hey Nadia,  I'm working with @JulieLev on this one.  **Very** early days but wondering if this structure would work (but as simplest thing)

So Alphabet would display, then viewer would click to find speaker.  However that isn't great for browsing........ so perhaps not a good approach?  You could have a 'Browse All' option? 

![alphabet_expand_list](https://user-images.githubusercontent.com/9321632/33663425-d49a471c-da87-11e7-974b-06dca38b685d.JPG)

Do you have a simpler idea? 

Thanks

**Comment by JulieLev** [comment]
![image](https://user-images.githubusercontent.com/19407259/33664448-9bbd5de0-da8b-11e7-8479-3420bb15a8e1.png)
Simple to start? Could look at splitting into columns afterwards if necessary? This isn't meant to be a design template, just a layout explanation!

**Comment by nodunayo** [comment]
Hey @JulieLev and @olwend!

Since we only have 30 speakers right now, I'm thinking something like columns on the speakers page will be the simplest thing to start.

Is there a way to automatically get it to split the list into 3 or 4 columns say, even as speakers are added?

I definitely like the alphabet idea and will consider it if/when (🤞) the speaker list grows, but given that most letters will have 0 speakers, and the maximum is 5 (two letters A and J), I think it'll be a lot for an experience that might be worse.

What do you think?

Nadia

P.S. Sorry for the slow response today!

**Comment by JulieLev** [comment]
Hi @nodunayo,

I'm actually really glad you pointed that out. Much more straightforward and shouldn't be difficult. Perhaps we just imagined your app growing so quickly! 

We didn't manage to get together this evening anyway but will give it a shot and put in a PR when ready, 

Thank you!

**Comment by nodunayo** [comment]
Hi @JulieLev,

I'm glad to hear it! And yes — hopefully it does grow and then we can revisit this idea.

Looking forward to the PR. No rush!

Speak soon,

Nadia

**Comment by JulieLev** [comment]
Just to let you know, @olwend and I did communicate on this - no snatching of issues here!

**Comment by nodunayo** [comment]
Yay, shipped! 🎉

It looks great.

Thank you, @JulieLev!
