### ISSUE TITLE
Upon failing to save a proposal, keep the submitter's progress!

### ISSUE THREAD

**Issue by nodunayo** [nodunayo/speakerline#35]
If you attempt to submit an invalid form at '/proposals/new' the form re-renders but it is blank!

It would be a much better user experience if the submitter's progress was saved so they correct their error rather than have to start again.

**Comment by Greg-Rose** [comment]
I'll take this one

**Comment by nodunayo** [comment]
Thanks, @Greg-Rose — will check this out later today.

**Comment by nodunayo** [comment]
Yay, shipped!

Thanks, @Greg-Rose. :-)
