### ISSUE TITLE
Feature-coupled step definitions

### ISSUE THREAD

**Issue by nodunayo** [nodunayo/speakerline#37]
@tomstuart pointed out [here](https://github.com/nodunayo/speakerline/pull/8/commits/d54fbd70b3f9aef8b485eaae03555e353a92748c) that the project was suffering from "feature-coupled step definitions".

Let's refactor the step definitions so that we're not susceptible to this pain!

**Comment by flyinggrizzly** [comment]
@nodunayo is it alright if I pick this up?

**Comment by nodunayo** [comment]
@flyinggrizzly I'm mid organising a pairing session with @tomstuart to complete this! I'll hang onto it for a few more weeks.

If we don't manage to do it by April, then I'll ping you to pick it up.

Thanks. :-)
