### ISSUE TITLE
Title box is too short

### ISSUE THREAD

**Issue by nodunayo** [nodunayo/speakerline#43]
When adding a proposal, the title is hardly ever, if ever, completely visible:

<img width="1064" alt="screen shot 2017-12-02 at 22 17 51" src="https://user-images.githubusercontent.com/4911302/33520248-d0f875e2-d7ae-11e7-8160-b08b7a655e38.png">

We should make it such that when filling out the form at /proposals/new, the submitter can see the whole title. This will help prevent typos too!

**Comment by olwend** [comment]
Hi, Im looking into this.  Thanks Olwen

**Comment by nodunayo** [comment]
No issues at all!

Don't worry about tests for this, I'd say!

**Comment by olwend** [comment]
Yes I thought test was overkill too  as it is  string - varchar so submitting PR 👍

**Comment by nodunayo** [comment]
Thank you, Olwen!
