### ISSUE TITLE
The blue used for links doesn't pass WCAG standards. 

### ISSUE THREAD

**Issue by hilarysk** [nodunayo/speakerline#568]
We could switch it to a darker version, and then it passes color contrast requirements: https://webaim.org/resources/contrastchecker/?fcolor=157D9D&bcolor=FFFFFF

Here's what it would look like:

<img width="1159" alt="Screen Shot 2024-05-08 at 11 50 38 AM" src="https://github.com/nodunayo/speakerline/assets/6457189/6894ed92-a2b4-459d-af3c-e1560ad60210">

<br><br>

**versus:**

<img width="1072" alt="Screen Shot 2024-05-08 at 11 51 47 AM" src="https://github.com/nodunayo/speakerline/assets/6457189/80f6ba0f-5710-4084-9cc2-62e06cb0741d">

**Comment by nodunayo** [comment]
Yes! Thank you! And I think the accessible blue actually looks better too.

**Comment by hilarysk** [comment]
Working on this one now 🙌🏻

**Comment by nodunayo** [comment]
Thank you, Hilary!
