### ISSUE TITLE
/admin path crashes because ActiveStorage is not configured

### ISSUE THREAD

**Issue by abeger** [nodunayo/speakerline#569]
Speakerline has no need for ActiveStorage, but [RailsAdmin](https://github.com/railsadminteam/rails_admin) seems to _require_ ActiveStorage. Not sure if this is a Speakerline config issue, a RailsAdmin config issue, or something else.

The actual error message:

```
RuntimeError in RailsAdmin::MainController#dashboard

Missing Active Storage service name. Specify Active Storage service name for config.active_storage.service in config/environments/development.rb
```

**Comment by nodunayo** [comment]
Hmm, yes, I definitely don't want it to be required at all! Are you looking into this right now or do you need me to?

**Comment by abeger** [comment]
I've (finally) got this figured out. PR coming soon.

**Comment by nodunayo** [comment]
Amazing!!
