### ISSUE TITLE
As a speaker, I want to be able to create a proposal from my speaker page pre-filled with my name

### ISSUE THREAD

**Issue by hilarysk** [nodunayo/speakerline#576]
From the speaker show page, add a button to create a proposal that pre-selects the speaker's name (this will make adding new proposals in a row much faster). 

<img width="1042" alt="Screen Shot 2024-05-08 at 4 05 04 PM" src="https://github.com/nodunayo/speakerline/assets/6457189/207b7ee4-f05e-4bc6-b8ce-c58dcd27aefa">

**Comment by hilarysk** [comment]
doing now 🤓

**Comment by nodunayo** [comment]
Thanks, Hilary!
