### ISSUE TITLE
App inaccessible because of SSL issue

### ISSUE THREAD

**Issue by flyinggrizzly** [nodunayo/speakerline#65]
This is probably due to the year change over, but https://speakerline.io isn't available right now.

<img width="1025" alt="screen shot 2018-01-01 at 10 52 36" src="https://user-images.githubusercontent.com/10967676/34467192-0c9c7be4-eee2-11e7-951b-9a6d6ac50580.png">

I'm not getting any more useful error messages on this...

paging @nodunayo -- figure app down is kind of a biggie!

Same issue on OS X in Chrome, Firefox, Opera and Safari

Is this possibly HSTS refusing to serve the app because the SSL certs are down/expired?

**Comment by flyinggrizzly** [comment]
Same issue on OS X in Chrome, Firefox, Opera and Safari

**Comment by nodunayo** [comment]
Hmmm!! Strange. Will look into it. Thank you!!

Nadia Odunayo

**Comment by nodunayo** [comment]
Hey, @flyinggrizzly.

It's because you're attempting to access Speakerline via https, but I don't have SSL set up yet. Only http for now!

(It's high up on my list to sort it out.)

**Comment by flyinggrizzly** [comment]
Oh dear... now I feel silly

**Comment by nodunayo** [comment]
Oh no, please don't! I feel silly for not having sorted SSL yet! 😁
