### ISSUE TITLE
Enum for Accepted, Rejected, Waitlisted should order like Acc, Wait, Rej

### ISSUE THREAD

**Issue by flyinggrizzly** [nodunayo/speakerline#67]
Seeing Accepted proposals at the top of a list of submissions for an event makes sense, but having Waitlisted props follow Rejected props is less clear.

Proposals should list

- Accepted
- Waitlisted
- Rejected

instead of as they do:
<img width="607" alt="screen shot 2018-02-02 at 20 22 27" src="https://user-images.githubusercontent.com/10967676/35753260-dedd6c34-0856-11e8-9a55-363c4e948054.png">

**Comment by nodunayo** [comment]
Fair enough! 🙂

**Comment by abeger** [comment]
I'll pick this one up.
